#include "pch.h"
#include "NetS4ModApi.h"


#define IMPLEMENT_CALLBACK_LIST(type, name) std::vector<Callback<type>*> name##List = std::vector<Callback<type>*>{};


IMPLEMENT_CALLBACK_LIST(S4WNDPROC, S4WndProc)

IMPLEMENT_CALLBACK_LIST(S4FRAMECALLBACK, S4FrameCallback)
IMPLEMENT_CALLBACK_LIST(S4FRAMECALLBACK, S4UIFrameCallback)
IMPLEMENT_CALLBACK_LIST(S4MAPINITCALLBACK, S4MapInitCallback)
IMPLEMENT_CALLBACK_LIST(S4MOUSECALLBACK, S4MouseCallback)
IMPLEMENT_CALLBACK_LIST(S4SETTLERSENDCALLBACK, S4SettlerSendCallback)
IMPLEMENT_CALLBACK_LIST(S4TICKCALLBACK, S4TickCallback)
IMPLEMENT_CALLBACK_LIST(S4LUAOPENCALLBACK, S4LuaOpenCallback)
IMPLEMENT_CALLBACK_LIST(S4BLTCALLBACK, S4BltCallback)
IMPLEMENT_CALLBACK_LIST(S4GUIBLTCALLBACK, S4GUIBltCallback)
IMPLEMENT_CALLBACK_LIST(S4ENTITYCALLBACK, S4EntityCallback)
IMPLEMENT_CALLBACK_LIST(S4GUIDRAWCALLBACK, S4GUIDrawCallback)
IMPLEMENT_CALLBACK_LIST(S4GUICLEARCALLBACK, S4GUIClearCallback)

int callbackIndex = 0;

LONG_PTR oldWndProc;
